# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: true
os:
  - linux
  - osx
julia:
  - 1.0
matrix:
  allow_failures:

notifications:
  email: false

script:
  - julia --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add("Test"); Pkg.add("BenchmarkTools"); Pkg.update(); include("test/runtests.jl")'


